### Levenstein distance
- #### Dimitris Georgiou - DS3517004
- #### Stratos Gounidellis - DS3517005
- #### Natasa Farmaki - DS3517018

In [1]:
import numpy as np

def levenstein_distance(word1, word2):
    distance = np.zeros((len(word1) + 1, len(word2) + 1)) 
    distance[0, :] = np.arange(len(word2) + 1)
    distance[:, 0] = np.arange(len(word1) + 1)
    for i in range(len(word1)):
        for j in range(len(word2)):
            # edit could also be 1
            edit = 2
            if word1[i] == word2[j]:
                edit = 0
            d1 = distance[i][j + 1] + 1
            d2 = distance[i + 1][j] + 1
            d3 = distance[i][j] + edit
            distance[i + 1][j + 1] = min(d1, d2, d3)
    return distance

def levenstein_distance_ext(word, vocabulary, dist):
    words = []
    for voc in vocabulary:
        distance = np.zeros((len(word) + 1, len(voc) + 1)) 
        distance[0, :] = np.arange(len(voc) + 1)
        distance[:, 0] = np.arange(len(word) + 1)
        for i in range(len(word)):
            for j in range(len(voc)):
                # edit could also be 1
                edit = 2
                if word[i] == voc[j]:
                    edit = 0
                d1 = distance[i][j + 1] + 1
                d2 = distance[i + 1][j] + 1
                d3 = distance[i][j] + edit
                distance[i + 1][j + 1] = min(d1, d2, d3)
        if distance[len(word)][len(voc)] <= dist:
            words.append(voc)
    return words

print(levenstein_distance("πέζοιται", "παίζετε"))


[[ 0.  1.  2.  3.  4.  5.  6.  7.]
 [ 1.  0.  1.  2.  3.  4.  5.  6.]
 [ 2.  1.  2.  3.  4.  5.  6.  7.]
 [ 3.  2.  3.  4.  3.  4.  5.  6.]
 [ 4.  3.  4.  5.  4.  5.  6.  7.]
 [ 5.  4.  5.  6.  5.  6.  7.  8.]
 [ 6.  5.  6.  7.  6.  7.  6.  7.]
 [ 7.  6.  5.  6.  7.  8.  7.  8.]
 [ 8.  7.  6.  7.  8.  9.  8.  9.]]
